### ISSUE TITLE
Extension release as separate package

### ISSUE THREAD

**Issue by KacerCZ** [deceze/Twig-extensions#2]
Do you have any plan to release Gettext extension as separate package, so it will not be tied with rest of extensions?

This would simplify extension management.

**Comment by deceze** [comment]
I am not currently actively using Twig for anything and do not have any plans for further development of this extension. You are very welcome to copy/fork/re-package the available code into a standalone package; I'd be happy if it continues to serve a purpose.

**Comment by KacerCZ** [comment]
OK
I prepared https://github.com/KacerCZ/twig-gettext-extension with only gettext extension.
